apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: hub-bridge-enp7s0
spec:
  desiredState:
    interfaces:
    - name: enp7s0
      state: up
      type: ethernet
    - bridge:
        options:
          stp:
            enabled: true
        port:
        - name: enp7s0
      ipv4:
        dhcp: true
        enabled: true
      name: br-hub
      state: up
      type: linux-bridge
  nodeSelector:
    node-role.kubernetes.io/BGPspeaker: ""
